### ISSUE TITLE
JSDOC looks too ugly

### ISSUE THREAD

**Issue by Devric** [nkbt/puma#1]
Use docco, unless you plan to css jsDoc, it puts people off

**Comment by nkbt** [comment]
I will style it 100%. That is just "default" template. Docco is cool for
reading, but is not good for internal annotating, that is used by PhpStorm
and other IDEs to guess types

## 

Sincerely yours, Nikita Butenko
Google Talk: nikita.butenko@gmail.com
Skype: nikita.butenko
Mobile: +61 450 264 801

**Comment by Devric** [comment]
try grunt-dox, i think dox generates compatible syntax with jsDoc, 
and also has foundation.css for reading.

I'm considering to migrate from docco to grunt-dox, but having an issue on grunter, probably incompatible to the latest grunt.
